# Generated by Django 3.2.7 on 2021-10-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='imagen1')),
                ('talla', models.CharField(max_length=30, verbose_name='Talla')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
            ],
        ),
    ]
